from typing import List, Any

class CNF:
    def __init__(self, from_clauses: Any = ...) -> None: ...
    def append(self, clause: List[int]) -> None: ...
    def extend(self, clauses: List[List[int]]) -> None: ...
    def __iter__(self) -> Any: ...
