from typing import List, Optional, Any

class Solver:
    def __init__(self, name: Optional[str] = ..., bootstrap_with: Any = ..., use_timer: bool = ...) -> None: ...
    def add_clause(self, clause: List[int]) -> None: ...
    def solve(self, assumptions: Optional[List[int]] = ...) -> bool: ...
    def get_model(self) -> Optional[List[int]]: ...
    def delete(self) -> None: ...
