"""Versioned artifacts, replay support, and regression-test generation."""

from __future__ import annotations

import asyncio
import dataclasses
import importlib
import json
import pprint
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, List, Mapping, Optional, Sequence, TYPE_CHECKING, Union

from .models import ConcolicResult, ExecutionOutcome, ExecutionTrace

if TYPE_CHECKING:
    from .engine import NativeConcolicEngine


ARTIFACT_SCHEMA = "aria.concolic/v1"


@dataclass(frozen=True)
class ReplayMismatch:
    """A difference between a recorded execution and a replay."""

    index: int
    field: str
    expected: Any
    actual: Any


@dataclass
class ReplayResult:
    """Traces obtained by replay and any stability violations."""

    traces: List[ExecutionTrace]
    mismatches: List[ReplayMismatch]

    @property
    def stable(self) -> bool:
        return not self.mismatches


class ArtifactStore:
    """Read and write portable JSON records for concolic campaigns."""

    def write(
        self,
        path: Union[Path, str],
        target: str,
        result: ConcolicResult,
        metadata: Optional[Mapping[str, Any]] = None,
    ) -> Path:
        destination = Path(path)
        destination.parent.mkdir(parents=True, exist_ok=True)
        payload = {
            "schema": ARTIFACT_SCHEMA,
            "target": target,
            "metadata": dict(metadata or {}),
            "result": self._encoded_result(result),
        }
        destination.write_text(
            json.dumps(payload, indent=2, sort_keys=True, ensure_ascii=False) + "\n",
            encoding="utf-8",
        )
        return destination

    def read(self, path: Union[Path, str]) -> Dict[str, Any]:
        payload = json.loads(Path(path).read_text(encoding="utf-8"))
        if payload.get("schema") != ARTIFACT_SCHEMA:
            raise ValueError(
                f"unsupported concolic artifact schema: {payload.get('schema')!r}"
            )
        if not isinstance(payload.get("result", {}).get("traces"), list):
            raise ValueError("concolic artifact has no trace list")
        return payload

    def replay(
        self,
        path: Union[Path, str],
        engine: "NativeConcolicEngine",
    ) -> ReplayResult:
        try:
            asyncio.get_running_loop()
        except RuntimeError:
            return asyncio.run(self.areplay(path, engine))
        raise RuntimeError("await ArtifactStore.areplay() inside an event loop")

    async def areplay(
        self,
        path: Union[Path, str],
        engine: "NativeConcolicEngine",
    ) -> ReplayResult:
        """Replay recorded inputs against synchronous or asynchronous targets."""
        payload = self.read(path)
        recorded = payload["result"]["traces"]
        traces = []
        mismatches = []
        for index, expected in enumerate(recorded):
            trace = await engine.atrace(_decode_value(expected["inputs"]))
            traces.append(trace)
            actual = trace.to_dict()
            for field in (
                "outcome",
                "path_signature",
                "exception_type",
                "exception_message",
            ):
                if expected.get(field) != actual.get(field):
                    mismatches.append(
                        ReplayMismatch(
                            index, field, expected.get(field), actual.get(field)
                        )
                    )
        return ReplayResult(traces, mismatches)

    def write_pytest_regressions(
        self,
        path: Union[Path, str],
        module_name: str,
        qualified_name: str,
        failures: Sequence[ExecutionTrace],
    ) -> Path:
        """Generate deterministic pytest tests for recorded exceptions."""
        destination = Path(path)
        destination.parent.mkdir(parents=True, exist_ok=True)
        lines = [
            '"""Generated by aria-concolic; edit or commit as a regression suite."""',
            "",
            "import importlib",
            "from aria.concolic.invocation import invoke_target_sync",
            "",
            "import pytest",
            "",
            f"_TARGET = importlib.import_module({module_name!r})",
            f"for _COMPONENT in {qualified_name.split('.')!r}:",
            "    _TARGET = getattr(_TARGET, _COMPONENT)",
            "",
        ]
        for index, trace in enumerate(failures):
            if trace.outcome != ExecutionOutcome.RAISED or not trace.exception_type:
                continue
            exception_module, _, exception_name = trace.exception_type.rpartition(".")
            lines.extend(
                [
                    f"def test_concolic_regression_{index}():",
                    f"    module = importlib.import_module({exception_module!r})",
                    f"    exception_type = getattr(module, {exception_name!r})",
                    f"    inputs = {pprint.pformat(trace.inputs, sort_dicts=True)}",
                    "    with pytest.raises(exception_type):",
                    "        invoke_target_sync(_TARGET, inputs)",
                    "",
                ]
            )
        destination.write_text("\n".join(lines), encoding="utf-8")
        return destination

    @staticmethod
    def _encoded_result(result: ConcolicResult) -> Dict[str, Any]:
        payload = result.to_dict()
        for trace in payload["traces"]:
            trace["inputs"] = _encode_value(trace["inputs"])
        payload["generated_inputs"] = [
            _encode_value(inputs) for inputs in result.generated_inputs
        ]
        return payload


def _encode_value(value: Any) -> Any:
    if value is None or isinstance(value, (bool, int, float, str)):
        return value
    if isinstance(value, list):
        return {"$aria": "list", "items": [_encode_value(item) for item in value]}
    if isinstance(value, tuple):
        return {"$aria": "tuple", "items": [_encode_value(item) for item in value]}
    if isinstance(value, dict):
        return {
            "$aria": "dict",
            "items": [
                [_encode_value(key), _encode_value(item)] for key, item in value.items()
            ],
        }
    if isinstance(value, set):
        return {
            "$aria": "set",
            "items": [_encode_value(item) for item in sorted(value, key=repr)],
        }
    if isinstance(value, bytes):
        return {"$aria": "bytes", "hex": value.hex()}
    if isinstance(value, bytearray):
        return {"$aria": "bytearray", "hex": bytes(value).hex()}
    if dataclasses.is_dataclass(value) or hasattr(value, "__dict__"):
        fields = (
            {
                field.name: getattr(value, field.name)
                for field in dataclasses.fields(value)
            }
            if dataclasses.is_dataclass(value)
            else dict(vars(value))
        )
        return {
            "$aria": "object",
            "module": type(value).__module__,
            "qualname": type(value).__qualname__,
            "fields": _encode_value(fields),
        }
    raise TypeError(f"artifact value of type {type(value).__name__} is not portable")


def _decode_value(value: Any) -> Any:
    if not isinstance(value, dict) or "$aria" not in value:
        return value
    kind = value["$aria"]
    items = value.get("items", [])
    if kind == "list":
        return [_decode_value(item) for item in items]
    if kind == "tuple":
        return tuple(_decode_value(item) for item in items)
    if kind == "dict":
        return {_decode_value(key): _decode_value(item) for key, item in items}
    if kind == "set":
        return {_decode_value(item) for item in items}
    if kind == "bytes":
        return bytes.fromhex(value["hex"])
    if kind == "bytearray":
        return bytearray.fromhex(value["hex"])
    if kind == "object":
        module = importlib.import_module(value["module"])
        owner: Any = module
        for component in value["qualname"].split("."):
            owner = getattr(owner, component)
        fields = _decode_value(value["fields"])
        try:
            return owner(**fields)
        except TypeError:
            instance = owner.__new__(owner)
            for name, item in fields.items():
                setattr(instance, name, item)
            return instance
    raise ValueError(f"unknown encoded artifact value kind {kind!r}")
