from typing import List, Optional, Any, ContextManager
from .fnode import FNode

def get_free_variables(formula: FNode) -> List[FNode]: ...
def Implies(left: FNode, right: FNode) -> FNode: ...

class Solver(ContextManager["Solver"]):
    def __init__(self, logic: Optional[Any] = ..., name: Optional[str] = ...) -> None: ...
    def add_assertion(self, formula: FNode) -> None: ...
    def solve(self) -> bool: ...
    def get_value(self, formula: FNode) -> FNode: ...
    converter: Any = ...  # Has back() method

def Not(formula: FNode) -> FNode: ...
def And(*formulas: FNode) -> FNode: ...
def Or(*formulas: FNode) -> FNode: ...
def EqualsOrIff(left: FNode, right: FNode) -> FNode: ...
def Symbol(name: str, type: Any) -> FNode: ...
